### ISSUE TITLE
Search for keyboard in both directories

### ISSUE THREAD

**Issue by Ordoviz** [it0946/socd#1]
My `/dev/input` directory looks as follows:
```
by-id
└── usb-Chicony_HP_HD_Webcam__Fixed_-event-if00 -> ../event15
by-path
├── pci-0000:00:1a.0-usb-0:1.3:1.0-event -> ../event15
├── platform-i8042-serio-0-event-kbd -> ../event3
├── platform-i8042-serio-1-event-mouse -> ../event8
├── platform-i8042-serio-1-mouse -> ../mouse0
├── platform-i8042-serio-4-event-mouse -> ../event14
├── platform-i8042-serio-4-mouse -> ../mouse1
└── platform-lis3lv02d-event -> ../event5
```
My keyboard is in `by-path` but socd doesn't find it because it only looks inside `by-id`, resulting in `error: Failed to get keyboards`.

**Comment by it0946** [comment]
Hello, thanks for the issue. When did you try this? I believe this should be fixed by now as SOCD first tries `by-id` and if that fails it then tries `by-path`

**Comment by Ordoviz** [comment]
I tried it a few hours ago on d083c4eb68c9824a283f5a6bd7a988517d4d9fb8. It seems that SOCD only tries `by-path` when `opendir(BY_ID)` fails:

```c
    if ((d = opendir(BY_ID)) != NULL)
        strcpy(context.rd_target, BY_ID);
    else if ((d = opendir(BY_PATH)) != NULL) {
        strcpy(context.rd_target, BY_PATH);
    } else 
        return 1;
```

**Comment by it0946** [comment]
I don't see why that would be an issue, does it not check properly after `opendir(BY_ID)` fails? After testing on my machine real quick it seemed to work fine

**Comment by it0946** [comment]
Oh wait. I realised your issue now. I'll get to fixing that

**Comment by it0946** [comment]
This should be fixed now, can you try doing now

**Comment by Ordoviz** [comment]
My keyboard is detected now, thanks!
